stderr to był błąd error out
terminate called after throwing an instance of 'std::range_error'
  what():  Index is out of range exception
